name: Test Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run checks
      run: |
        cargo check --verbose
        cargo fmt -- --check
        cargo audit

    - name: Run tests
      run: |
        cargo test -- --nocapture --test-threads 1
        cargo test --release -- --nocapture --test-threads 1
